### ISSUE TITLE
Toggle layout

### ISSUE THREAD

**Issue by smartmeter** [David-Desmaisons/Vue.Isotope#1]
Hi, can you add toggle layout

**Comment by David-Desmaisons** [comment]
Hi @smartmeter , I am not sure what do you mean by toggle layout. Could you be more specific?

**Comment by smartmeter** [comment]
hi @David-Desmaisons , I am trying to get the tiles to resize/or toggle like [this](http://bit.ly/1xJkK3k), can you show me how to do it.

thanks

**Comment by David-Desmaisons** [comment]
I just comited:
-an update on isotope example with layout toogle
-a fix on existing method to change layout.
I will release a new version with this fix shortky

**Comment by David-Desmaisons** [comment]
Just release new version with fix + updated readme.

**Comment by smartmeter** [comment]
Hi the downloaded files do not run, they have place holders showing in the samples.

```
Togle Layout

Similarly, it is possible to update the layout mode using the following method:

  this.isotopeArrange(arrangeOption, id);
```

I saw this help note, can you please tell me what is the `arragneOption` and the `Id`represent or how to use them when I call them from the server side

**Comment by David-Desmaisons** [comment]
arragneOption should be same value as isotope arrange accepts. For example:

```
{
  filter: '.metal',
  sortBy: 'number'
}
```

Please refer to isotope documentation for complete description.

if the viewmodel display only one isotope  component id can be undefined. Otherwise it should be the same value as id value of the option argument.

**Comment by David-Desmaisons** [comment]
Regarding the download, how did you "download" the files?

**Comment by smartmeter** [comment]
Hi, I used the clone / download link from your page. I am trying to get the toggle working, and its not for me, let me try some more. thanks :+1:

**Comment by David-Desmaisons** [comment]
OK, I recomend using bower or npm to get last stable version.
