### ISSUE TITLE
Switch to isotope-packery, or add option for isotope-packery.

### ISSUE THREAD

**Issue by bcwp** [David-Desmaisons/Vue.Isotope#10]
We're using vue.isotope but are running into a problem, vueisotope uses isotope-layout which doesn't have the packery layout option. Ideally there should be some way to use isotope-packery (v2) instead.

**Comment by David-Desmaisons** [comment]
you can change layout, see this fiddle:
https://jsfiddle.net/dede89/d117mj5u/

You may have install packery layout package with bower or npm. Please check isotope documentation to this respect.

---

De : bcwp notifications@github.com
Envoyé : jeudi 6 octobre 2016 02:26
À : David-Desmaisons/Vue.Isotope
Objet : [David-Desmaisons/Vue.Isotope] Switch to isotope-packery, or add option for isotope-packery. (#10)

We're using vue.isotope but are running into a problem, vueisotope uses isotope-layout which doesn't have the packery layout option. Ideally there should be some way to use isotope-packery (v2) instead.

##
