### ISSUE TITLE
Vue.js 2.0 Support

### ISSUE THREAD

**Issue by Mark-A-Richardson** [David-Desmaisons/Vue.Isotope#11]
Just wondering when this will undated to support Vue.js 2.0?

I am currently running into 'Cannot read property 'params' of undefined' on line 45 of 'Vue.Isotope/src/vue_isotope.js'.

**Comment by David-Desmaisons** [comment]
Hello @Mark-A-Richardson , I am currently working on it.
In Vue.js 2.0, a component will be used to integrate vue and isotope,

**Comment by David-Desmaisons** [comment]
version 2.0 is compatible with Vue.js 2.0.
