### ISSUE TITLE
Support prepending items

### ISSUE THREAD

**Issue by mediavrog** [David-Desmaisons/Vue.Isotope#14]
Hi there, first of all thanks for the isotope binding with vue. Saved a lot of headaches already! Great work :+1:

In my usecase I have a list of links with newest being at the top left of the grid. If a new link is added, it will be appended to the bottom of the list, whereas it should be on the top according to sort order. Reading the isotope docus, it should be possible using the prepend method instead of insert.
Docs: http://isotope.metafizzy.co/v1/docs/adding-items.html#prepending

I'd like to see support for this as an option? for vue-isotope.

**Comment by David-Desmaisons** [comment]
Hi @mediavrog , could you please create a simple jsfidle with your usecase, so it will be easier to understand the problem ans provide a solution. Thanks.

**Comment by mediavrog** [comment]
Thanks for getting back so quick. I'll try to post an example this week

**Comment by mediavrog** [comment]
Hey @David-Desmaisons , I reviewed my code again and it actually works if a sorting is defined properly. New elements will still appear at the end of the list but will immediately be sorted according to your sorting specified. So no need for my request as it can be mitigated using sorting.
