### ISSUE TITLE
vue isotope for vue cli/webpack?

### ISSUE THREAD

**Issue by gstrobl** [David-Desmaisons/Vue.Isotope#15]
Hello, is your package running on a vue cli/webpack installation? I tried your example code, but it didn't work. 

```
  import Vueisotope from 'vueisotope'
  export default {
    components: {
      'isotope': Vueisotope
    },
    data () {
      return {
        layouts: [
          'masonry',
          'fitRows',
          'cellsByRow',
....
```
This is my error:
`Unknown custom element: <isotope> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Do have a solution for my problem?

**Comment by David-Desmaisons** [comment]
@gstrobl : See repository [Readme](https://github.com/David-Desmaisons/Vue.Isotope#webpack-and-browserify-usage):  
#### Webpack and Browserify usage:
  Be aware of isotope recomendation for usage with [Webpack](http://isotope.metafizzy.co/extras.html#webpack) and [Browserify](http://isotope.metafizzy.co/extras.html#browserify)

**Comment by gstrobl** [comment]
Yeah, I have read it. But do you have a solution for my problem?

**Comment by David-Desmaisons** [comment]
From the mentioned documentation:

Install Isotope with npm.
```
npm install isotope-layout
```

In your config file, webpack.config.js, add these resolve aliases.
```
module.exports = {
  resolve: {
    alias: {
      'masonry': 'masonry-layout',
      'isotope': 'isotope-layout'
    }
  }
};

```
