### ISSUE TITLE
Images Loaded

### ISSUE THREAD

**Issue by jdg5** [David-Desmaisons/Vue.Isotope#16]
Hi,

Firstly, thank you for making this :) 

I was trying to figure out how to add ImagesLoaded JS (by the same people who made Isotope) to Vue.Isotope. That will help solve my layout issues upon loading.

Cheers.

**Comment by David-Desmaisons** [comment]
Hello @jnjdg , could you provide a jsfiddel explaining waht you are trying to achieve and what is going wrong? 
Thanks

**Comment by jdg5** [comment]
Hi David,

Thanks for the quick response! The JSFiddle doesn't properly show it but I can explain it very simply. The images have a large file size and do not load fully before isotope executes it's layout so it shows partly loaded photos. 

I am trying to execute Isotope after the images are fully loaded and not halfway through, but I don't know how to do that with your vue-isotope. Any ideas greatly appreciated :)

http://imagesloaded.desandro.com/

**Comment by jdg5** [comment]
Sorry to bother again. So is there a way to call Isotope after the images have loaded? Perhaps with the Vue 'Mounted' function...? 

Thanks

**Comment by David-Desmaisons** [comment]
Hi @jnjdg , it will help if you could provide a simple jsfidle example so that it could be used as a base to make this works.
I should have more time next week to investigate this issue.

**Comment by David-Desmaisons** [comment]
@jnjdg , please check [vue.imagesLoaded](https://github.com/David-Desmaisons/Vue.ImagesLoaded#isotope-example) directive to solve this problem.
