### ISSUE TITLE
Filters are removing every item and crushes

### ISSUE THREAD

**Issue by adrian1207** [David-Desmaisons/Vue.Isotope#18]
Hi,

for first: great job, thanks!

But one small problem. I can't get filters to work.

I have filtering method like in demo:
`filter: function() {
            this.$refs.grid.filter('all');
        },`

Options like:
`sortBy: 'by_nick',
                getSortData: {
                    by_nick: function(user) {
                        return user.nick.toLowerCase();
                    },
                    by_age: function(user) {
                        return user.age;
                    }
                },
                getFilterData: {
                    all: function() {
                        return true;
                    }
                }`
And html:
`<isotope ref="grid" :list="users" :options='isotopeOptions()'>
                <div class="user" v-for="user in users">
                    <user v-on:invite="eventInvite({{ Auth::user()->id }}, user.id)" :user="user" self="{{ Auth::user()->id }}"></user>
                </div>
            </isotope>`

Sorting is working, but filtering is removing all items, no matter what I will return in filter function.

I think thats why Im getting error:
`Uncaught TypeError: Cannot read property 'vm' of undefined`

Do you might help, whats going on?

BTW. while npm installation, gulp crushes on trying load node_modules/masonry, coz that lib is called node_modules/masonry-layout originally, i think :)

**Comment by David-Desmaisons** [comment]
@adrian1207 , could you create a jsfiddle please? It is quite didficult to understand what is going on just with this code sample.

**Comment by adrian1207** [comment]
Ok, I found what was the problem.

Somehow, Isotope reqired in node before jQuery is different than the same require after jQuery. This is why module.exports from your plugin gave me an object with empty '__underlying_element'.

So this notatnition:
```
window._ = require('lodash');
window.vueIsotope = require('vueisotope');
window.$ = window.jQuery = require('jquery');
Vue.component('isotope', window.vueIsotope);
```
works perfectly, but this:
```
window._ = require('lodash');
window.$ = window.jQuery = require('jquery');
window.vueIsotope = require('vueisotope');
Vue.component('isotope', window.vueIsotope);
```
works, but while filtering gives error:
`Uncaught TypeError: Cannot read property 'vm' of undefined`
in 47 line of vue_isotope.js:
`const res =  getItemVm(itemElement); return value.call(this, res.vm, res.index);`

But anyway problem is solved. Thanks. :)

**Comment by David-Desmaisons** [comment]
Thanks for reporting that you found a solution. 
I am closing the issue.
