### ISSUE TITLE
Example for using events

### ISSUE THREAD

**Issue by aliph5** [David-Desmaisons/Vue.Isotope#19]
This is a great vue component for using isotope! 

However, I can't seem to figure out how to use events. Specifically, I'd like to do some additional handling of my VM when arrange and sort events are emitted. An example in the readme would be great.

Thanks.

**Comment by David-Desmaisons** [comment]
@aliph5 , you can find example using events in the example folder of the project: [component.html](https://github.com/David-Desmaisons/Vue.Isotope/blob/master/examples/component.html)

**Comment by abbas-fahm** [comment]
@David-Desmaisons thanks, i'm trying to do some post-processing after the arrange is called.

`<isotope :list="row" id="root_isotope" @arrange="testFunction()" class="isoDefault" :options='option' >`

But I'm not seeing this being triggered.

**Comment by David-Desmaisons** [comment]
@abbas-fahm It should be

```@arrange="testFunction"```

**Comment by David-Desmaisons** [comment]
Please see [metal.html](https://github.com/David-Desmaisons/Vue.Isotope/blob/master/examples/metal.html) for an example usage of isotope with events `filter`, `sort`, `layout`
