### ISSUE TITLE
Layout ends up only vertical

### ISSUE THREAD

**Issue by wilkesreid** [David-Desmaisons/Vue.Isotope#2]
In the demo given in README.md ( https://jsfiddle.net/dede89/d117mj5u/ ) clicking the layout buttons "masonry" and "masonryHorizontal" and switching back and forth will eventually cause the layout to go completely vertical.

I am in Chrome 52.0.2743.116 (64-bit) on a MacBook Pro Retina 13-inch OS X El Capitan ver. 10.11.6.
![vue_gif](https://cloud.githubusercontent.com/assets/509805/17703247/9f976dd8-6396-11e6-88de-a4057326f8d1.gif)

**Comment by David-Desmaisons** [comment]
Hello @wilkesreid, 
the only think done by  vue_istope is to call isotope arrange method with different layouts:

```
this.isotopeArrange({
        layoutMode: key
      });
```

```
 isotopeArrange: function(layout, id){
                    getIso(id).arrange(layout);
                  }
```

If the layout is not behaving as expected, you may open issue on [isotope](https://github.com/metafizzy/isotope) project.
Thanks
