### ISSUE TITLE
TypeError: Cannot read property 'vm' of undefined when using component with jQuery

### ISSUE THREAD

**Issue by MintyOrb** [David-Desmaisons/Vue.Isotope#20]
I may be dense, but when trying to use your component with vue-router I get `TypeError: Cannot read property 'vm' of undefined` when trying to use the filter function. Sorting and layout both work before trying to filter, but after they break with the same error.

[Here is a live example of the issue.](http://vue-router-isotope.surge.sh/#/e) In this case there's a router.js and main.js and the template for the isotope router-view is inline in the router file. Any idea what's going wrong?

**Comment by David-Desmaisons** [comment]
Hello @bornytm , It seems that in presence of jQuery the isotope component sends event with diferrent parameters. Coudl you please to remove the jquery tag script and see if the problem still hapens?

**Comment by David-Desmaisons** [comment]
@bornytm , could please use isJQueryFiltering=false in the isotope option and tell me if this resolve the issue?

**Comment by MintyOrb** [comment]
Both using isJQueryFiltering=false in the options and removing jquery entirely seems fixes the issue. Thanks!

**Comment by David-Desmaisons** [comment]
@bornytm cool! I will release a version where isotope component forces isJQueryFiltering=false. Untill I release this version, you can set isJQueryFiltering=false manually.

**Comment by David-Desmaisons** [comment]
Fixed in version 2.1.0
