### ISSUE TITLE
sortAscending option not supported when passed in as a reference

### ISSUE THREAD

**Issue by MintyOrb** [David-Desmaisons/Vue.Isotope#21]
Providing the `sortAscending` option directly ( ` sortAscending: true`) works with no problem, however when passed as a reference to a value on the vue object (so that it can be toggled: `sortAscending: this.upDown`), it breaks with `TypeError: Cannot read property '[object String]' of undefined`. Is this not supported or am I doing something wrong? Perhaps I should also ask if this is just a stupid thing to try and do.

Thanks!

```
data: function () {
    return {
      upDown: true,
      option: {
        sortAscending: this.upDown
      }
    },
    methods: {
      sort: function(key) {
        this.$refs.isotope.sort(key);
      }
  });
```

**Comment by David-Desmaisons** [comment]
@bornytm , This is the same as issue #22 , use a method that return option and it will work

**Comment by MintyOrb** [comment]
@David-Desmaisons your solution worked for the other issue, but to get sortAscending working I needed to add `sortAscending: this.options.sortAscending` to your sort function within the component:

```
   sort (name) {
          this.arrange({sortBy  :name, sortAscending: this.options.sortAscending})
          this.$emit("sort", name)
        },
```
