### ISSUE TITLE
"this" not set as underlying vm for getFilterData functions

### ISSUE THREAD

**Issue by MintyOrb** [David-Desmaisons/Vue.Isotope#22]
It seems "this" from the vue instance vm is not made available to the getFilterData functions. No error is thrown because it is just filtering on "undefined". Filtering works when directly inserting text:`return el.description.includes('hello')`.
```
data: function () {
  return {
    searchStr: null,
    option: {
      getFilterData: {
        "contains": function(el) {
          console.log(this.searchStr) // undefined when called
          return el.description.includes(this.searchStr)
        }
      }
    }
  }
});
```

**Comment by David-Desmaisons** [comment]
@bornytm , If you want to access to the vm for option as `this`, you cant you a method:

```HTML
<isotope :options="getOptions">
```

```javascript
methods:{
 getOptions: {
      return {
        getFilterData: {
            "contains": function(el) {
             console.log(this.searchStr) // undefined when called
            return el.description.includes(this.searchStr)
          }
        }
     }
  }
}
```

**Comment by MintyOrb** [comment]
Thank you David! I realized it was the same issue shortly after posting but wouldn't have thought to use a method on my own. And again, thanks for producing this component- it's very handy.

**Comment by MintyOrb** [comment]
Still stuck unfortunately...

Using `<isotope :options="getOptions()">` and
```
 methods:{
 getOptions: function() {
      return {
        getFilterData: {
            "contains": function(el) {
             console.log(this.searchStr) // undefined when called
            return el.description.includes(this.searchStr)
          }
        },
        sortAscending: this.upDown,
        itemSelector: ".element-item",
        getSortData: {
                    rating: "rating",
                    viewcount: "viewcount",
                   ...
                },
     }
  }
}
```
doesn't seem to make the function available on the vue data object. I'm getting the error `vue.js:525 [Vue warn]: Property or method "getFilterData" is not defined on the instance but referenced during render.` I get the same error for sortAscending and getSortData

Right now I'm suing `<button v-for="(val, key) in getFilterData"....` and `  <button v-for="(val, key) in getSortData"` like in your example.

**Comment by David-Desmaisons** [comment]
Could you create a jsfiddle please?

**Comment by MintyOrb** [comment]
Sure thing-[ here you go.](https://jsfiddle.net/1a32bzm5/31/)

**Comment by David-Desmaisons** [comment]
Here you, here is the corrected fiddle:

https://jsfiddle.net/dede89/w1tbv83L/7/


Tweaks: 

1) getFilterData and getSortData were not defined in data , so I added filterData and sortData
2) ```v-for="(val, key)```  key and val were inverted
3) To have the correct context in the getFilterData contains function, I used ES6 arrow function to capture viewModel context (you can do it by hand if you use ES5 using ```var ctx=this...```):

```javascipt
getFilterData: {
    "show all": function() {
         return true;
   },
    "contains": (el) => {
         return el.description.includes(this.searchStr)
   }
 },
```

And it worked like a charm....
