### ISSUE TITLE
missing masonry module

### ISSUE THREAD

**Issue by 2mhost** [David-Desmaisons/Vue.Isotope#26]
I got this error when using isotope component 

./~/isotope-layout/js/layout-modes/masonry.js
Module not found: Error: Can't resolve 'masonry/masonry' in 'node_modules\isotope-layout\js\layout-modes'

installation went fine with no errors.

**Comment by David-Desmaisons** [comment]
Hello @2mhost , please refer to [readme](https://github.com/David-Desmaisons/Vue.Isotope#webpack-and-browserify-usage). 
Using masonry require an extra webpack configuration

**Comment by rolivagon** [comment]
@2mhost you should solved the error with masonry ? I Have the same problem.

**Comment by 2mhost** [comment]
Sorry for the delay, Yes, I solved the error .. you need to add resolve aliases to your webpack.config file as described here:

https://isotope.metafizzy.co/extras.html#webpack

**Comment by rolivagon** [comment]
Thanks, @2mhost after write here I solved !!
