### ISSUE TITLE
I'm not able to run isotope properly

### ISSUE THREAD

**Issue by lucaguada** [David-Desmaisons/Vue.Isotope#28]
I started a new project with vue-cli and installed isotope by using npm. I modified the webpack references as shown in the readme, then I just tried to mimic the demo:

```
<template>
      <isotope :list="list" id="root_isotope" class="isoDefault" :options="option">
        <div v-for="element in list" @click="selected = element" :key="element.id">
          {{element.title}}
          <br> {{element.author}}
        </div>
      </isotope>
</template>

<script>
import Vue from 'vue'
import isotope from 'isotope'

Vue.use(isotope)

new Vue({
  ...
})
</script>
```

But there's no way to make it work, Vue complains about isotope element:
```
[Vue warn]: Unknown custom element: <isotope> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

I also tried different combinations of imports by importing lodash and istope-layout manually but nothing to do. Any idea on what I'm doing wrong?

**Comment by David-Desmaisons** [comment]
Do not use `Vue.use(isotope)` that will not perform anything.

Use like this on vue file (a specified in the readme):
```
// ES6
import isotope from 'vueisotope'
...
export default {
      components: {
        isotope,
      }
      ...
```

**Comment by SadRebel1000** [comment]
Hello,

I'm just taking some first steps using Javascript, Vue and Isotope. I've tried hours to make a copy of the js.fiddle vue-istope-chemistry-example to work offline (main.js + main.html +main.css), but I can't get it work and get the same problem as above. 

`var Vue = require('vue');
var lodash = require('lodash');
var Isotope = require('vueisotope');

var count = 0;

var vm = new Vue({  el: "#main",
  data: {
    layouts: [
...`

I use npm and browserify to build a bundle.js which I load in the main.html file. When I load the website, the web console tells me the same warning as above. Some of the things are there but it doesn't work and has no layout. 
I read the readme file and checked on the isotope website and tried to fulfil the recommendations as requested but clearly I don't quite understand. I also tried installing and requiring jQuery and jQueryBridget but nothing works...

Please, let me know if you need any other information from me to help. I understand that I'm asking a bit of hazy question...
