### ISSUE TITLE
ReLoad Items

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [David-Desmaisons/Vue.Isotope#29]
Hi,

currently i'm running into the problem, when updating my list of elements via AJAX, i cannot re-initialize isotope - it displays only the initial elements.
In the isotope docs (https://isotope.metafizzy.co/methods.html#reloaditems) is a funtion "reloadItems" which might solve my problem but vue-isotope tells me, that this is not a function (called with `this.$refs.productGrid.reloadItems()`)

Is there by any chance a possibility to call all native isotope functions? Or does your plugin provide a function like this? Or any other solution?

Thank you in advance!

**Comment by David-Desmaisons** [comment]
@hurradieweltgehtunter, I think this is a use case for [vue.imagesLoaded](https://github.com/David-Desmaisons/Vue.Isotope#working-with-images). See [isotope example](https://github.com/David-Desmaisons/Vue.ImagesLoaded#isotope-example)

**Comment by hurradieweltgehtunter** [comment]
kindof solved my problem. Thank you
