### ISSUE TITLE
set default filter

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [David-Desmaisons/Vue.Isotope#30]
Hi again,
your docs say "Full support of Isotope options via options parameters" but setting a default filter doesn't work. 

```
isotopeOptions: {
  itemSelector: '.oc-product',
  filter: 'filter1', // what must be entered here? css class? or same as in getFilterData?
  getFilterData: {
    "show all": function() {
      return true
    },
    filter1: function(el) {
      return el.type === 'filter1'
    }
  }
}
```

Is this possible? If so, how?

Thank you!

**Comment by David-Desmaisons** [comment]
@hurradieweltgehtunter , you should use the filter method of the vue component.
See this fiddle as an example:

https://jsfiddle.net/dede89/1a32bzm5/42/

**Comment by hurradieweltgehtunter** [comment]
If i do so, the filtered out items will be visible for a short amount of time.
Also, i don't know when the isotope element has finished rendering. So i don't know when to set the filter.

Besides, this is not "full support" of isotope options

**Comment by David-Desmaisons** [comment]
In version 3.1.0, it is possible to set default filter using filter parameter:

```javascript
isotopeOptions: {
  filter: 'filter1', // reference a getFilterData parameter
  getFilterData: {
    "show all": function() {
      return true
    },
    filter1: function(el) {
      return el.type === 'filter1'
    }
  }
}
```

As you see, this is "full support" of isotope options :wink:

**Comment by hurradieweltgehtunter** [comment]
not tested yet but thank you for updating!

**Comment by hctpbl** [comment]
I tried to test it but I get an error when the component is initialized:

`Cannot read property 'getFilterData' of undefined`

So it seems that the `_isotopeOptions` variable is undefined. Weird thing is, if I change the package.json to use the non minified version of the component (`src/vue_isotope.js`), this works great. I don't see the 3.1.0 release here in gitHub either. Could it be a problem with the published dist code?
