### ISSUE TITLE
fns.apply is not a function when using a filter

### ISSUE THREAD

**Issue by mrcasual** [David-Desmaisons/Vue.Isotope#33]
Hi,

I am getting this odd error when clicking on a filter (the actual filter works though): 

```
app.js:42886 Uncaught TypeError: fns.apply is not a function
    at VueComponent.invoker (app.js:42886)
    at VueComponent.Vue.$emit (app.js:43355)
    at VueComponent.l (app.js:50847)
    at VueComponent.boundFn [as filter] (app.js:41313)
    at VueComponent.filter (app.js:1003)
    at Proxy.boundFn (app.js:41313)
    at click (app.js:41065)
    at HTMLAnchorElement.invoker (app.js:42886)
```

My filter is pretty straightforward:

```
<a @click="filter('a')">Test 1</a>
<a @click="filter('b')">Test 2</a>

methods: {
  filter: function (key) {
    this.$refs.cpt.filter(key);
  }
}
...
```

Latest versions of both libraries:

```
"vue": "^2.1.10"
"vueisotope": "^3.1.0"
```

If you have any idea as to why this is happening, I'd love to hear them.

Thanks.

**Comment by David-Desmaisons** [comment]
Do you declare the ref attribute on the isotope component (for your example: ` ref="cpt"`)?

If you do, please create a jsfiddle, if you don't, this explains the error.

**Comment by mrcasual** [comment]
I am creating a ref and the filter function works despite the error. I'll try to create a jsfiddle but given that I am using webpack and nesting components, it may be difficult to do.

**Comment by mrcasual** [comment]
I can't replicate this by separately including all libraries. I am using a fresh install of Laravel 5.4 with its default webpack configuration, so the problem could be specific to that setup. Thanks.
