### ISSUE TITLE
Overlapping image

### ISSUE THREAD

**Issue by HugoRomat** [David-Desmaisons/Vue.Isotope#36]
`<isotope :options='{}' :list="galleryImage" id="root_isotopeCaption">`
     `    <plantCaption v-for="plantCaption in galleryImage" v-bind:plantCaption="plantCaption" :key="plantCaption.guid">`
`     </plantCaption>`
`</isotope>        `     

And my template : 
`<img v-bind:src="plantCaption.imageURL">`

And all my images overlapp themselves. 

People seems to have the same issues here : [https://stackoverflow.com/questions/13959579/isotope-folded-elements-overlap](https://stackoverflow.com/questions/13959579/isotope-folded-elements-overlap)

Could you tell me how to fix it ? 

Cheers

**Comment by David-Desmaisons** [comment]
Use [Vue.ImagesLoaded](https://github.com/David-Desmaisons/Vue.ImagesLoaded)
