### ISSUE TITLE
Complex filters in computed

### ISSUE THREAD

**Issue by preetamslot** [David-Desmaisons/Vue.Isotope#42]
Hi,
is there a way to use your own computed filters on the :list object?

```
<div v-isotope-for="element in filteredList" :options='option' @click="selected=element">
```

```
computed: {
    filteredList: function(){
     //my custom complex filters
     return .......
  }
},
```
Thanks!

**Comment by David-Desmaisons** [comment]
Are you using version for vue 1?
For vue 2, see this jsfiddle:
https://jsfiddle.net/dede89/g6c0vzm2/

**Comment by preetamslot** [comment]
Thanks for the quick response!
Im using the vue 2 version. 
The The filters in the demo are defined in the data part of the app.

The point is that I got some advanced array filters that (I think) needs to be in the computed area of the app.

so instead of feeding the data to isotope and use the filter of isotope I would like to pass filtered data into isotope, and update the data with the computed filter. 

If its not possible, no problem, Just checking if there is a way to make this work.

Thanks again!

**Comment by David-Desmaisons** [comment]
In the jsfiddle, the filter is based on:
` return itemElem.name.toLowerCase().includes(this.filterText.toLowerCase());`

Well filterText could be a computed property or a props, it will work as well.
