### ISSUE TITLE
Not ES6 compatible?

### ISSUE THREAD

**Issue by MintyOrb** [David-Desmaisons/Vue.Isotope#45]
Trying to use this component with Vue 2.5.8 and webpack 3.8.1 I get a `Uncaught ReferenceError: require is not defined` where vueisotope is requireing lodash.

**Comment by David-Desmaisons** [comment]
Which version?

**Comment by MintyOrb** [comment]
vueisotope 3.1.1 and using vue-loader 12.2.2

**Comment by MintyOrb** [comment]
Not sure what was wrong with config I had when this error occured, but in a new project with vue-cli it's working just fine.
