### ISSUE TITLE
How can i pass additional params to isotope

### ISSUE THREAD

**Issue by nickaguilarh** [David-Desmaisons/Vue.Isotope#49]
I'm trying to pass some additional params to isotope.
`
$('.grid').isotope({
  itemSelector: '.grid-item', // use a separate class for itemSelector, other than .col-
  **percentPosition: true,**
  masonry: {
    **columnWidth: '.grid-sizer'**
  }
});
`
those params, 
how can i do that? i have no clue if it should be included in getOptions Method.
I'm Using Vue.Js 2
This is the metods im using. 
`
getOptions: function () {
                var _this = this
                return {
                    getFilterData: {
                        none: function () {
                            return true;
                        },
                        filterByCategory: function (itemElem) {
                            return itemElem.category.name.toLowerCase() ==
                                _this.$refs.cat.$data.filterOption.toLowerCase();
                        },
                    }
                };
            },
            layout () {
                this.$refs.iso.layout('masonry');
            },
`

**Comment by David-Desmaisons** [comment]
Use [options](https://github.com/David-Desmaisons/Vue.Isotope#options) props.
