### ISSUE TITLE
"props,"  IE11 and SCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by SadRebel1000** [David-Desmaisons/Vue.Isotope#60]
Hi there, 

I've been getting further along in using vue.isotope. I'm looking into browser compatibility and hit the wall concerning Internet Explorer. 
On Win10 and IE11 I get a `SCRIPT1003: Expected ':'` error.  It happens in the vue.isotope 'props,' line:

```
    var isotopeComponent = {
      name: 'isotope',

      props,
```

I've been using stuff like babelify  (preset-env) but it doesn't really help. 
Might I have fallen on a bug? Or am I stupidly missing something?

ps. whenever I have time a will add an example in the closed 'combination filter' issue, because I did found a solution (but did not have time put the essence in js.fiddle).

**Comment by David-Desmaisons** [comment]
Looks like you are using the src version and not the dist version: https://github.com/David-Desmaisons/Vue.Isotope/blob/master/dist/vue_isotope.js
 (after compilitaion).

**Comment by SadRebel1000** [comment]
Strange, I use npm install. I will look into it further, and reopen if needed. I'm missing a setting in browserify then, I will look into it...

**Comment by SadRebel1000** [comment]
Still need to learn a lot, sorry for the hassle, and thanks!

**Comment by jhaya93** [comment]
Hello SadRebel1000,
Can you explain to me the way you had the 'combination filter' working ?
I'm strugling with this.

Thank you

**Comment by SadRebel1000** [comment]
You can find a description of the solution here: https://github.com/David-Desmaisons/Vue.Isotope/issues/47#issuecomment-502398573 . I'm sorry but at the time I don't have time to help more (It's been more then 4 years already).

**Comment by jhaya93** [comment]
Thank you SadRebel1000, i will go this way
