### ISSUE TITLE
Adding a new item to list always appends

### ISSUE THREAD

**Issue by TheFrankman** [David-Desmaisons/Vue.Isotope#62]
Hello There, 

When I add an item to the list, no matter how I do it, it always gets appended to the end of the list.

for example 

```
<isotope v-images-loaded:on.progress="layout" ref="cpt" :list="artwork" id="root_isotope" class="isoDefault" :options='option' sort-ascending="false">
    <div class="grid-item" v-for="element in artwork" @click="selected=element"  :key="element.id">
        ....
    </div>
</isotope>
```

```
data: () => ({
    ...
    option: {
                layoutMode: 'masonry',
                masonry: {
                    gutter: 10
                },
                columnWidth: '.grid-sizer',
                itemSelector: '.grid-item',
                sortBy : 'created_at',
                sortAscending : false
            }
    ...
```

```
EventBus.$on('upload-success', payload => {
    if (payload && payload.length) {
        this.addedItemsOffset += payload.length;
        this.artwork = payload.concat(this.artwork);
        // this.$refs.cpt.sort('created_at')
        // this.$refs.cpt.arrange()
    }
});
```
The concat should re-arrange the list so the new items received from the payload array are put to the beginning of the list. When using the vue console, or logging the list to the console I can see that my new items have been added to the beginning of the list, yet isotope appends them.

I have attempted re-sorting `this.$refs.cpt.sort('created_at')` and the arrange method `this.$refs.cpt.arrange()` as well as using various other things as the sort, for example ID would work as the new ones will always have a higher id.

**Comment by David-Desmaisons** [comment]
Hello @TheFrankman , could you create a jsfiddle reproducing this issue please?
