### ISSUE TITLE
Support of animationEngine

### ISSUE THREAD

**Issue by zakarialounes** [David-Desmaisons/Vue.Isotope#67]
Hello,
There is a way to define option for animationEngine?
Thanks in advance

**Comment by David-Desmaisons** [comment]
Could you explain better? What is animationEngine?

**Comment by zakarialounes** [comment]
This is an option which allows to choose between CSS3 transitions or jQuery (relative and absolute positioning), cf. https://isotope.metafizzy.co/v1/docs/options.html#animationengine

**Comment by zakarialounes** [comment]
Sorry for the Issue, is no more available since Isotope v2... thanks
