### ISSUE TITLE
Vue.Isotope fails to register with Vue when using Vue loader

### ISSUE THREAD

**Issue by MintyOrb** [David-Desmaisons/Vue.Isotope#7]
This issue may not be directly with Vue.Isotope, but given the popularity of using vue with webpack/vue-loader I thought it was worth trying to resolve. I'm also not ruling out the possibility that I'm doing something really stupid.

I'm trying to use this excellent directive in my webpack app using vue-loader but it seems I can get the Vue instance to see the directive. 

I've tried loading it in every place I can think, but I'm clearly missing something, perhaps due to my relative unfamiliarity with webpack.

Calling `Vue.use` after importing the directive in `main.js` doesn't seem to register the directive across components- I get the error `[Vue warn]: Failed to resolve directive: isotope (found in component: <hello>)`.

Should I be registering the component in a different location? Any suggestions would be appreciated.

```
//main.js
import Vue from 'vue';
import App from './App';
import Vueisotope from 'Vueisotope'
Vue.use(Vueisotope)

new Vue({
  el: 'body',
  components: { App }
})
```

```
//App.vue
<template>
  <hello></hello>
</template>

<script>
import Hello from './components/Hello'

export default {
  components: {
    Hello
  }
}
</script>
```

```
//Hello.vue
<template>
  <div v-isotope="element in list">
    <p>{{element.name}}</p>
  </div>
</template>

<script>
export default {
  data () {
    return {
      list:
      [{'name':'one'}, {'name':'two'},{'name': 'woah'},]
    }
  }
}
</script>
```

**Comment by David-Desmaisons** [comment]
Hello @bornytm , Two thinks here: 
1) the name of the directive is "v-isotope-for" and not "v-isotope" : I have updated the read.me documentation which was wrong.
2) The isotope elements should be wrapped inside a div (I will document this rigth now).

The correct markup should be:

```
<template>
    <div>
        <div v-isotope-for="element in list">
            <p>{{element.name}}</p>
        </div>
   </div>
</template>

```
