### ISSUE TITLE
Changes in items don't update isotope

### ISSUE THREAD

**Issue by p0psicles** [David-Desmaisons/Vue.Isotope#78]
It seems that changes in the items prop do not update the isotope. 

I've implemented a textbox that filters the items (through) a computed. 

Is there a way to make vue-isotope respond to changes in the items array? 

Or some other way to filter on a specific object property?

**Comment by yingban** [comment]
@p0psicles You can re-render your component by dynamically changing your your key component.
https://michaelnthiessen.com/force-re-render/

**Comment by p0psicles** [comment]
Tnx, I knew of the key attribute. But the article gave me some new insights. Tnx.
