### ISSUE TITLE
Destroy on mobile, reInitialize on tablet/desktop

### ISSUE THREAD

**Issue by microcipcip** [David-Desmaisons/Vue.Isotope#8]
Is it possible to destroy isotope on mobile and re-initialize on tablet/desktop?

**Comment by David-Desmaisons** [comment]
Hello @microcipcip , I am not sure I understand your question. Could you be more specific?

**Comment by microcipcip** [comment]
I have a isotope grid that needs to be initialized only on tablet/desktop and not on mobile device width. Do you know if that is possible? See [this method](http://isotope.metafizzy.co/methods.html#destroy). So if I resize the browser window isotope should be destroyed, and re-initialized if the window is bigger...

**Comment by David-Desmaisons** [comment]
You can detect if your are in a mobile context using javascript see for example: [this stackooverflow question](http://stackoverflow.com/questions/3514784/what-is-the-best-way-to-detect-a-mobile-device-in-jquery),
Better than callin destroy you can condition the usage of isotope directive to the fact that you are in not in mobile context:

``` HTML
<div v-if="isMobile">
    <div v-for="element in elements">
    </div>
</div>
<div v-else>
    <div v-isotope-for="element in elements">
    </div>
</div>
```

**Comment by microcipcip** [comment]
Thanks, that was my conclusion also, I thought there was some other way of doing it. Thanks for your time,  very useful vue directive :)

P.S. It seems that [it may be possible to pass a parameter from the parent](http://v1.vuejs.org/guide/custom-directive.html#params) to the directive with `paramWatchers`, so maybe it is possible to call the destroy method, but your solution is the easiest way of doing it.

```
Vue.directive('example', {
  params: ['a'],
  paramWatchers: {
    a: function (val, oldVal) {
      console.log('a changed!')
    }
  }
})
```

```
<div v-example v-bind:a="someValue"></div>
```
