### ISSUE TITLE
Get id when using isotopeLayout(id);

### ISSUE THREAD

**Issue by microcipcip** [David-Desmaisons/Vue.Isotope#9]
How do you fire a certain layout if you have multiple grid components? I don't understand how I get the `id` property. Here is an example: 

```
<component-1
  v-isotope-for="post in posts"
  :options="postGridOpts"
  :data="myData",
  track-by="$index"
><slot></slot></component-1>

<component-2
  v-isotope-for="post in posts"
  :options="postGridOpts"
  :data="myData",
  track-by="$index"
><slot></slot></component-2>
```

Then in the parent component I have:

```
ready() {
  Vue.nextTick(() => {
    this.isotopeLayout(); // What ID?
  });
}
```

**Comment by David-Desmaisons** [comment]
Here is an example of use of two isotope layout with the same vm:
https://jsfiddle.net/dede89/8w1o535m/6/

the id is pass by the option parameters

NB: you do not need to call isotopeLayout on ready as isotope-for directive calls it automatically. Only call isotopeLayout, when you need to change the options.
